// <auto-generated />
using System;
using IISPSupdate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IISPSupdate.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260226170707_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IISPSupdate.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScanSource")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("IISPSupdate.Models.ProjectRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowReboot")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorPolicy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HangfireJobId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxConcurrency")
                        .HasColumnType("int");

                    b.Property<bool>("OnlineOnly")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledForUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectRuns");
                });

            modelBuilder.Entity("IISPSupdate.Models.ProjectRunServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectRunId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectServerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectServerId");

                    b.HasIndex("ProjectRunId", "ProjectServerId")
                        .IsUnique();

                    b.ToTable("ProjectRunServers");
                });

            modelBuilder.Entity("IISPSupdate.Models.ProjectServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Environment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fqdn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastScanAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreFlightError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreFlightStatus")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectServers");
                });

            modelBuilder.Entity("IISPSupdate.Models.ServerScanResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectServerId")
                        .HasColumnType("int");

                    b.Property<string>("RawOutput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScanSource")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScanTimeUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectServerId");

                    b.ToTable("ServerScanResults");
                });

            modelBuilder.Entity("IISPSupdate.Models.ServerSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KbNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectServerId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectServerId");

                    b.ToTable("ServerSelections");
                });

            modelBuilder.Entity("IISPSupdate.Models.UpdateCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSelectedByDefault")
                        .HasColumnType("bit");

                    b.Property<string>("KbNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServerScanResultId")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ServerScanResultId");

                    b.ToTable("UpdateCandidates");
                });

            modelBuilder.Entity("IISPSupdate.Models.ProjectRun", b =>
                {
                    b.HasOne("IISPSupdate.Models.Project", "Project")
                        .WithMany("Runs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("IISPSupdate.Models.ProjectRunServer", b =>
                {
                    b.HasOne("IISPSupdate.Models.ProjectRun", "ProjectRun")
                        .WithMany("Servers")
                        .HasForeignKey("ProjectRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IISPSupdate.Models.ProjectServer", "ProjectServer")
                        .WithMany()
                        .HasForeignKey("ProjectServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProjectRun");

                    b.Navigation("ProjectServer");
                });

            modelBuilder.Entity("IISPSupdate.Models.ProjectServer", b =>
                {
                    b.HasOne("IISPSupdate.Models.Project", "Project")
                        .WithMany("Servers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("IISPSupdate.Models.ServerScanResult", b =>
                {
                    b.HasOne("IISPSupdate.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IISPSupdate.Models.ProjectServer", "ProjectServer")
                        .WithMany("ScanResults")
                        .HasForeignKey("ProjectServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("ProjectServer");
                });

            modelBuilder.Entity("IISPSupdate.Models.ServerSelection", b =>
                {
                    b.HasOne("IISPSupdate.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IISPSupdate.Models.ProjectServer", "ProjectServer")
                        .WithMany()
                        .HasForeignKey("ProjectServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("ProjectServer");
                });

            modelBuilder.Entity("IISPSupdate.Models.UpdateCandidate", b =>
                {
                    b.HasOne("IISPSupdate.Models.ServerScanResult", "ServerScanResult")
                        .WithMany("Candidates")
                        .HasForeignKey("ServerScanResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServerScanResult");
                });

            modelBuilder.Entity("IISPSupdate.Models.Project", b =>
                {
                    b.Navigation("Runs");

                    b.Navigation("Servers");
                });

            modelBuilder.Entity("IISPSupdate.Models.ProjectRun", b =>
                {
                    b.Navigation("Servers");
                });

            modelBuilder.Entity("IISPSupdate.Models.ProjectServer", b =>
                {
                    b.Navigation("ScanResults");
                });

            modelBuilder.Entity("IISPSupdate.Models.ServerScanResult", b =>
                {
                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
